// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func UploadForm(profile Profile) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"clip_upload_form\" hx-encoding=\"multipart/form-data\" hx-post=\"/api/upload\"><div class=\"mb-3\"><label for=\"friendly_name\" class=\"form-label\">Clip Name</label> <input type=\"text\" class=\"form-control\" id=\"friendly_name\" aria-describedby=\"friendly_nameHelp\"><div id=\"friendly_nameHelp\" class=\"form-text\">Name of the uploaded clip</div></div><div class=\"mb-3\"><label for=\"game_name\" class=\"form-label\">Game Name</label> <input type=\"text\" class=\"form-control\" id=\"game_name\" aria-describedby=\"game_nameHelp\"><div id=\"game_nameHelp\" class=\"form-text\">Name of the game the clip is from</div></div><div class=\"mb-3\"><input type=\"file\" id=\"file\"></div><button type=\"submit\" class=\"btn btn-primary\">Submit</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
